import { T } from '../../catalog/helpers.js';
import type { ModeDef, PromptGuide } from '../../catalog/types.js';
import type { SeedanceKey } from './seedance/profile.js';
import type { SeedreamKey } from './seedream/profile.js';

/**
 * BytePlus 官方提示词指南的要点（提炼，不是原文；给 agent 写提示词用，MCP 的 get_model_schema 会返回）。
 * 来源页面与 revision 见各条 source；原文更新后用 `arkcli docs get <url> --outline` 对比 revision 再同步。
 * 个别条目改写成了本平台的说法（例如用参数而不是 API 字段名）。
 */
const CHECKED_AT = '2026-10-10';

export const SEEDREAM_50_EDITING_GUIDE: PromptGuide = {
  id: 'seedream-5-0-editing',
  // 官方只演示了普通参考图编辑（没有透明背景、图层分解）
  modes: ['generate'],
  title: T('Seedream 5.0 pro / flash 交互式编辑指南', 'Seedream 5.0 pro / flash interactive editing guide'),
  source: { url: 'https://ai.byteplus.com/ark/region:ap-southeast-1/docs/seedream-5-0-pro-editing-guide', revision: 296, checkedAt: CHECKED_AT },
  summary: T('pro/flash 的交互式编辑把坐标直接写进提示词：推荐给每个坐标标上所属图片 Image N，再用 <point>x y</point> 标点、用 <bbox>x1 y1 x2 y2</bbox> 标框。坐标按那一张图自身归一化到 0–999，嵌在一句"动作 + 带坐标的目标 + 结果"的自然语言指令里。框里有多个主体时用文字点明要改哪个；需要保持不变的区域也可以框出来，并写明 keep unchanged。', 'Seedream 5.0 pro/flash interactive editing embeds coordinates in the prompt: label each tag with its image (Image N, recommended) and use <point>x y</point> or <bbox>x1 y1 x2 y2</bbox>, normalized 0–999 per image, inside a natural-language "action + located target + result" instruction. Name the target in words when a box holds several subjects, and optionally box the regions to keep with an explicit "keep unchanged".'),
  rules: [
    { text: T('提示词里用 <point>x y</point> 标一个点，用 <bbox>x1 y1 x2 y2</bbox> 标一个矩形（先左上角 x1 y1，后右下角 x2 y2），数值都是用空格分隔的整数。', 'Mark a location with <point>x y</point> or a rectangle with <bbox>x1 y1 x2 y2</bbox> (top-left corner first, then bottom-right), using space-separated integers.'), modes: ['generate'] },
    { text: T('坐标相对被标注的那一张图本身，归一化到 0–999（左上角 0,0，右下角 999,999）：x = round(x_px / 图宽 × 1000)，y = round(y_px / 图高 × 1000)，结果超出范围就截到 0 或 999。像素坐标和宽高用同一套尺度即可（用原图像素；官方 demo 用画布显示尺寸，比例相同）。', 'Coordinates are relative to the annotated image itself, normalized to 0–999 (top-left 0,0, bottom-right 999,999): x = round(x_px / width × 1000), y = round(y_px / height × 1000), clamped to 0–999. Use one consistent scale for pixels and size (original image pixels work; the official demo uses the displayed canvas size, same ratio).'), modes: ['generate'] },
    { text: T('明确每个坐标属于哪张图：推荐在坐标前写所属图片的标签，例如 Image 1 <point>520 460</point>（只有一张图时也建议写 Image 1）。', 'Make clear which image each coordinate belongs to; the recommended form puts the image label before the tag, e.g. Image 1 <point>520 460</point> (recommended even with a single image).'), modes: ['generate'] },
    { text: T('提示词里的 Image N 指第 N 张输入图：本平台按参考图槽（assets.image）的传入顺序提交，Image 1 就是第一张。', 'Image N in the prompt is the Nth input image: this platform submits the reference-image slot (assets.image) in the order given, so Image 1 is the first one.'), modes: ['generate'] },
    { text: T('只想指向某个物体、让模型自己判断影响范围时用 point；需要精确控制编辑区域大小时用 bbox。', 'Use a point to indicate an object and let the model decide the affected area; use a bbox when the size of the edited region must be controlled precisely.'), modes: ['generate'] },
    { text: T('坐标要嵌在一句自然语言编辑指令里，句式是"动作 + 带坐标的目标 + 结果"，例如 Replace the object at Image 1 <point>…</point> with a crown. 或 Replace the area of Image 1 <bbox>…</bbox> with a garden.', 'Embed coordinates in one natural-language edit instruction: action + located target + result, e.g. "Replace the object at Image 1 <point>…</point> with a crown." or "Replace the area of Image 1 <bbox>…</bbox> with a garden."'), modes: ['generate'] },
    { text: T('跨图编辑时，来源图和目标图的位置都要标出来，例如 Place the subject from Image 1 <bbox>…</bbox> at the position of Image 2 <bbox>…</bbox>，或 Use the subject in Image 2 <bbox>…</bbox> to replace the subject in Image 1 <bbox>…</bbox>。', 'For cross-image edits, locate both source and destination: "Place the subject from Image 1 <bbox>…</bbox> at the position of Image 2 <bbox>…</bbox>" or "Use the subject in Image 2 <bbox>…</bbox> to replace the subject in Image 1 <bbox>…</bbox>".'), modes: ['generate'] },
    { text: T('一条提示词里可以混用点和框、做多处编辑，各个操作之间用 ", and …" 连起来。', 'A single prompt may mix points and boxes and carry several edits, chained with ", and …".'), modes: ['generate'] },
    { text: T('框里有多个主体或元素时，用文字点明要改的是哪一个，例如 the person on the left、the cat wearing a hat、the flower in the foreground。', 'When a bbox covers several subjects or elements, name the target in words, e.g. "the person on the left", "the cat wearing a hat", "the flower in the foreground".'), modes: ['generate'] },
    { text: T('需要保持原样的物体也可以用 bbox 框出来，并明确写 keep … unchanged 或 do not modify。', 'You can also box the objects that must stay as they are and state "keep … unchanged" or "do not modify" explicitly.'), modes: ['generate'] },
    { text: T('bbox 的两个角先按 min/max 排成左上和右下，超出图片的部分截到图片边界以内，然后再换算成 0–999 坐标。', 'Order bbox corners into top-left/bottom-right (min/max) and clip them to the image bounds before converting to 0–999.'), modes: ['generate'] },
    { text: T('交互式编辑没有专门的参数：在参考图槽（assets.image）里放至少 1 张待编辑的图，再写带坐标和编辑指令的提示词。', 'Interactive editing has no dedicated parameter: put at least one image to edit in the reference-image slot (assets.image) and write a prompt with coordinates and the edit instruction.'), modes: ['generate'] },
  ],
  examples: [
    { prompt: 'Replace the coffee mug at Image 1 <point>468 612</point> with a small potted cactus.', note: '单图点选：只指向一个物体，影响范围交给模型判断', modes: ['generate'] },
    { prompt: 'Replace the man on the right in Image 1 <bbox>540 210 910 980</bbox> with a bronze statue, and keep the area Image 1 <bbox>60 150 420 970</bbox> unchanged.', note: '框里有多个主体时用文字点明目标，并把要保持不变的区域另框出来、写明 unchanged', modes: ['generate'] },
    { prompt: 'Place the dog from Image 2 <bbox>205 340 780 955</bbox> on the sofa at Image 1 <bbox>150 420 860 900</bbox>, and replace the object at Image 1 <point>880 260</point> with a floor lamp.', note: '跨图编辑：框出来源图和目标图的位置，同一句里再加一处点选替换', modes: ['generate'] },
  ],
};

export const SEEDREAM_4X_GUIDE: PromptGuide = {
  id: 'seedream-4-x',
  title: T('Seedream 4.0-4.5 提示词指南', 'Seedream 4.0-4.5 prompt guide'),
  source: { url: 'https://ai.byteplus.com/ark/region:ap-southeast-1/docs/seedream-4-0-5-0-prompt-guide', revision: 296, checkedAt: CHECKED_AT },
  summary: T('用连贯的自然语言写"主体 + 动作 + 环境"，需要时补风格、色彩、光线、构图；写明用途和图像类型，图中文字放在双引号里，措辞宁可简洁准确，不要堆砌辞藻。编辑和参考生成要明确说出要改的目标、要保留什么、要从参考图提取什么；多图输入按 Image 1/2/3 分别交代每张图的作用；组图用 "a set/a series" 或直接写出张数来触发。', 'Write coherent natural-language prompts as subject + action + environment, adding style, color, lighting or composition when needed. State the purpose and image type, put any in-image text in double quotes, and keep the wording concise and precise instead of stacking ornate words. For edits and reference-based generation, name the target, what must stay unchanged and what to take from the reference. With several input images, refer to them as Image 1/2/3 and say what each one contributes. Trigger a series with "a set", "a series" or an explicit image count.'),
  rules: [
    { text: T('用连贯的自然语言句子描述「主体 + 动作 + 环境」，在意美感时再补风格、色彩、光线或构图；不要写成逗号分隔的关键词堆。', 'Describe subject + action + environment in coherent natural-language sentences, adding style, color, lighting or composition when aesthetics matter; do not write comma-separated keyword lists.') },
    { text: T('措辞简洁、准确，不要反复堆砌华丽复杂的形容词（4.x 理解力强，用较少的描述就能出预期效果）。', 'Keep wording concise and precise; do not pile up ornate, repetitive adjectives (4.x understands prompts well and needs less description).') },
    { text: T('画面复杂时，逐个元素交代位置、外观、上面的文字和颜色，以及光线方向和背景，以便精确控制。', 'For complex scenes, describe each element in turn (position, appearance, any text or colors on it) plus light direction and background, to control the result precisely.') },
    { text: T('有明确用途时，直接写明图像的用途和类型（如：为游戏公司设计 logo、海报、信息图、分镜）。', 'When there is a concrete use case, state the image\'s purpose and type explicitly (e.g. a logo for a gaming company, a poster, an infographic, a storyboard).') },
    { text: T('需要出现在画面里的文字一律用双引号括起来，例如 a poster with the title "XXX"。', 'Put any text that must appear in the image inside double quotes, e.g. a poster with the title "XXX".') },
    { text: T('需要特定风格时，用精确的风格关键词（如 picture book style、children\'s book illustration style），或上传一张风格参考图。', 'For a specific style, use precise style keywords (e.g. picture book style, children\'s book illustration style) or upload a style reference image.') },
    { text: T('公式、图解、教学插图等知识类内容，用准确的专业术语，并写明可视化形式、版式和风格（如：写在黑板上、每个原因单独配一个图标）。', 'For knowledge content such as formulas, diagrams or educational illustrations, use precise technical terms and state the visualization format, layout and style (e.g. on a blackboard, each cause shown separately with an icon).') },
    { text: T('编辑指令用「添加 / 删除 / 替换 / 修改」直接说，用可区分的属性指定目标（最高的、最大的、从左到右），不用 that one 这类含糊代词，并明确写出哪些保持不变（姿势、表情、原有风格）。', 'Phrase edits as add / remove / replace / modify, identify the target by a distinguishing attribute (tallest, largest, left to right) instead of vague pronouns like "that one", and state explicitly what stays unchanged (pose, expression, original style).'), modes: ['generate', 'group'] },
    { text: T('目标区域难以用文字说清时，在输入图上用箭头、框或涂鸦做标记，提示词里按颜色指代它（如 where the red area is marked、match the red box）。', 'When the target region is hard to describe in words, mark it on the input image with arrows, boxes or doodles and refer to the mark by color in the prompt (e.g. where the red area is marked, match the red box).'), modes: ['generate', 'group'] },
    { text: T('用参考图时写清两件事：① 要从参考图提取并保留什么（角色设计、画风、产品材质、服装款式）；② 要生成的新画面的细节（场景、布局、主体位置）。', 'When using a reference image, state (1) what to extract and keep from it (character design, art style, product material, clothing style) and (2) the details of the new scene to generate (setting, layout, subject position).') },
    { text: T('草图、线框图、平面图转高保真图时：提供清晰的原图；图中有文字标注就写「根据图中文字生成」；写明主体和目标（如高保真 UI、现代客厅）；写明哪些必须和参考图一致（布局、家具摆放）；必要时写明不要保留草图上的文字和手绘线条。', 'To turn a sketch, wireframe or floor plan into a high-fidelity image: give a clear original; if it has text annotations, say to generate based on the text in the image; state the subject and target (e.g. hi-fi UI, modern living room); state what must match the reference (layout, furniture placement); if needed, exclude the sketch\'s text and hand-drawn edges.') },
    { text: T('传了多张图时，用 Image 1、Image 2、Image 3 分别指称，并逐张写明从哪张取什么、改哪张，例如 Replace the subject in Image 1 with the subject from Image 2。', 'With several input images, refer to them as Image 1, Image 2, Image 3 and state what to take from or change in each, e.g. Replace the subject in Image 1 with the subject from Image 2.') },
    { text: T('组图用 a series、a set 或直接写出张数来触发，并逐张列出各自的内容（分镜场景、星期几），把需要统一的元素（主色、风格、角色）写在一起，保证连贯。', 'Trigger a series with "a series", "a set" or an explicit image count; list each image\'s content (storyboard scene, weekday) and state the shared elements (main color, style, character) to keep the set consistent.'), modes: ['group'] },
  ],
  examples: [
    { prompt: 'A concert poster for a jazz night: a saxophonist playing under a warm spotlight on a small stage, deep navy background, art deco style. The title "Blue Note Friday" appears in gold at the top.', note: '文生图：自然语言写主体+动作+环境+风格，写明用途（海报），画面文字放进双引号', modes: ['generate'] },
    { prompt: 'Dress the character in Image 1 with the leather jacket from Image 2, and render the result in the watercolor style of Image 3. Keep the pose, face and background of Image 1 unchanged.', note: '多图输入：按 Image 1/2/3 分别说明每张图的作用，并明确哪些保持不变', modes: ['generate'] },
    { prompt: 'Generate a set of four storyboard images of a cat\'s morning: waking on a windowsill, stretching, chasing a sunbeam, napping in a basket. Same orange cat in every frame, soft picture book style.', note: '组图：用 a set 加张数触发，逐张列出内容，并写明统一的角色和风格', modes: ['group'] },
  ],
};

export const SEEDANCE_25_GUIDE: PromptGuide = {
  id: 'seedance-2-5',
  title: T('Dreamina Seedance 2.5 提示词指南', 'Dreamina Seedance 2.5 prompt guide'),
  source: { url: 'https://ai.byteplus.com/ark/region:ap-southeast-1/docs/seedance-2-5-prompt-guide', revision: 296, checkedAt: CHECKED_AT },
  summary: T('先按上传顺序给每个素材编号（Image 1 / Video 1 / Audio 1），在文字里逐个写清它的用途；再用"一句话概括（主体+地点+事件+风格+运镜）→ 按整秒时间戳或 Shot N 分段写画面、运镜、动作、对白、音效 → 补充全程保持一致的要素"来组织。编辑和延长必须带触发词；严格对齐画面用关键帧，分镜图只作宽松参考；字幕、BGM 可以用否定写法压制，但不保证完全消除。', 'Number every asset by upload order (Image 1 / Video 1 / Audio 1) and bind each one in the text with its purpose. Then structure the prompt as a one-sentence summary (subject + location + event + style + camera), followed by integer-second timestamped or Shot N segments describing visuals, camera, action, dialogue and sound, and finally the elements that stay consistent throughout. Edit and extend prompts need trigger words. Use keyframes for strict alignment; storyboards are only loose references. Negatives can suppress subtitles and BGM but cannot guarantee their removal.'),
  rules: [
    { text: T('按上传顺序给素材编号（Image 1 / Video 1 / Audio 1），并在提示词文字里逐个绑定，写明每个素材是做主体、声音、动作、场景还是别的用途；不要只把名字写在图片上，再在提示词里直接用这个名字。', 'Number assets by upload order (Image 1 / Video 1 / Audio 1) and bind each one explicitly in the prompt text with its purpose (subject, voice, action, scene, etc.); never rely on a name written only inside the image.'), modes: ['omni', 'edit', 'extend'] },
    { text: T('写明每个素材参考的是什么，只参考一部分时写清是哪一部分（如"参考 Video 1 的施法动作和 Video 2 的环绕运镜""参考 Image 1 的光线和滤镜"）；素材本身已经足够准确时，直接写"严格参考 Video 1 的动作和运镜"，不要再重复描述细节。', 'State what each asset is a reference for, and which part when only part applies (e.g. \'the spell-casting action in Video 1, the orbit camera in Video 2\'); if the asset is already accurate, just say \'strictly follow the actions and camera in Video 1\' instead of re-describing it.'), modes: ['omni', 'edit', 'extend'] },
    { text: T('多主体时逐条列出映射关系，人多时用列表（如"Images 1-2 是角色 1，对应 Audio 1；Images 3-4 是角色 2，对应 Audio 2"）；按角色首次出场的顺序上传素材，让编号和出场顺序一致，避免角色和参考图错配。', 'For multiple subjects, list mappings one by one (use a list when there are many, e.g. \'Images 1-2 are Character 1 with Audio 1\'); upload assets in the order the subjects first appear so numbering matches appearance order.'), modes: ['omni'] },
    { text: T('提示词结构：先写一句话概括（主体 + 地点 + 事件 + 题材/风格 + 运镜），再按时间戳或"Shot N"分段，逐段写画面、运镜、动作、对白、音效，最后补充全程保持一致的机位、环境、声音、氛围等要素。', 'Structure: a one-sentence summary (subject + location + event + genre/style + camera movement), then timestamp or \'Shot N\' segments each describing visuals, camera, action, dialogue and sound, then notes on elements that stay consistent throughout.') },
    { text: T('时间戳以 1 秒为基本单位，时间段要首尾相接、不留空档（0-3s… 3-7s… 7-15s，不要写成 0-3s… 5-6s）；每段的内容量要合理，太少模型会自由发挥，太多会跳切或漏情节；也可以写时间点（第 5 秒）或相对时间（3 秒后）；不要用时间戳控制高频动作（如每秒摇头三次）。', 'Use 1-second units for timestamps with continuous, gap-free ranges (0-3s, 3-7s, 7-15s); keep content per range reasonable (too little invites improvisation, too much causes cuts or omissions); time points (\'at the 5-second mark\') and relative times also work; don\'t time high-frequency actions.') },
    { text: T('尽量用正面描述。指南支持对字幕和音频用否定写法（No subtitles；No BGM, only ambient and action sounds；No audio），但不能保证完全消除；要尽量去掉 BGM 时，把 music、BGM、score、instrumental、melody、synth、ambient pad 等词全部列出来，并在开头和结尾各写一遍；希望输出不带字幕时，作为参考的视频本身也不要带字幕。', 'Prefer positive descriptions. The guide supports negatives for subtitles and audio (\'No subtitles\', \'No BGM; only ambient and action sounds\', \'No audio\') but they cannot guarantee full removal; to suppress BGM, enumerate music/BGM/score/instrumental/melody/synth/ambient pad and repeat them at the start and end; to avoid subtitles in the output, use subtitle-free reference videos.') },
    { text: T('编辑任务要包含编辑触发词（edit video / add / insert / remove / delete / modify / replace / change to），写清修改范围，尽量写成"从 A 改为 B"，局部修改用时间戳（如"Video 1 第 4-6 秒把喝咖啡改成拖地，其余不变"）；多个参考和编辑要求混在一起时，拆成几次参考或编辑任务来做。', 'Edit prompts must contain an edit trigger (edit video / add / insert / remove / delete / modify / replace / change to), scope the change and phrase it as A to B, using timestamps for partial edits (\'4-6s in Video 1 ... leave the rest unchanged\'); split complex combined tasks into passes.'), modes: ['edit', 'omni'] },
    { text: T('延长任务要包含延长触发词（extend forward / extend backward / continue / continue from / extend the story），有多段视频时点名要延长哪一段（如 "Extend @Video 1 backward: …"），再描述新增内容；衔接效果最好的做法是源视频用 mov，并把输出格式（output_format 参数）设为 mov。', 'Extend prompts must contain an extension trigger (extend forward / extend backward / continue / continue from / extend the story), name which video to extend when several are given, then describe the new content; for the best continuity, use MOV source videos and set output_format to mov.'), modes: ['extend', 'omni'] },
    { text: T('首尾帧优先用首帧 / 首尾帧模式（i2v_first、i2v_first_last）的帧槽：输出比例锁定为首帧比例，首尾两张图要同比例，否则尾帧会被拉伸。也可以在全模态参考（omni）里把图作为参考图传入，并在提示词里写 "Image 1 is the first frame, Image 3 is the last frame"（不锁比例，结果只是近似）。', 'Prefer the frame slots of the i2v_first / i2v_first_last modes: the output ratio locks to the first frame, so use same-ratio images or the last frame gets stretched. Alternatively pass them as reference images in omni and write "Image 1 is the first frame, Image 3 is the last frame" (ratio not locked, only approximate).'), modes: ['i2v_first', 'i2v_first_last', 'omni'] },
    { text: T('画面要严格对齐时，把每张分镜作为单独的图按顺序上传，并在提示词第一句写"Use Images 1 to N in order as keyframes."。多格分镜图只作情节层面的宽松参考：最好不超过 15 格，用简单的线稿或火柴人，图上不要加文字；提示词按"素材映射 → 整体故事概括 → 按分镜补全动作、运镜、风格"三步写。', 'For strict alignment, upload each storyboard frame as a separate image and open with \'Use Images 1 to N in order as keyframes.\' Multi-panel storyboards are loose references only (≤15 panels, simple line art, no text); prompt as asset mapping → story summary → per-shot details.'), modes: ['omni'] },
    { text: T('用 3D 白模视频做参考时，写明参考它的哪些元素（运镜、动作，有光线变化时也写光线变化）；用颜色或编号把模型对应到参考图（如"把 Video 1 里的红色模型换成 Image 1 中穿灰衣的男人"）；仍要详细描述想要的画面，并和白模内容保持一致。', 'With a 3D clay-model video, state which elements to reference (camera movement, motion, and lighting changes if any), map models to reference images by color (\'replace the red model in Video 1 with the man in Image 1\'), and still describe the content in detail, consistent with the clay video.'), modes: ['omni'] },
    { text: T('常见景别、运镜、角度、技法可以直接写（wide shot / push in / orbit / low angle / one-shot / dolly zoom / FPV / bullet time 等）；太冷门或太专业的术语写成"术语 + 描述性解释"；转场要同时写清触发时间和转场方式（如"第 5 秒左划转场叠加自然溶解"）。', 'Write standard shot sizes, moves, angles and techniques directly (wide shot, push in, orbit, low angle, one-shot, dolly zoom, FPV, bullet time); expand niche terms as \'term + plain explanation\'; for transitions give both timing and method (\'at 5s, a left wipe with a dissolve\').') },
    { text: T('动作以概括描述为主，只给少数关键动作写细节，不要重复同一动作；表情用描述性句子，少用成语；不要用 fanatical、extremely shocked 这类强烈情绪词，改用 amazed 等中性词，必要时补一句 normal eyes, no glowing eyes，避免眼睛发光。', 'Describe actions in general terms, detailing only a few key moments and never repeating actions; write expressions as descriptive sentences, not idioms; replace intense emotion words with neutral ones (\'amazed\') and add \'normal eyes, no glowing eyes\' to avoid glowing pupils.') },
    { text: T('对白（示例统一用 {} 包裹）要给不同台词不同演绎时，用"Character\'s line (emotion): {content}"逐行写，不要在台词后面重复其中的词再附语气说明（容易触发字幕）；画面里必须写对的文字，拆成单个字母要求依次出现，或把正确文字做成参考图，并写"referring to Image N"。', 'For per-line delivery use "Character\'s line (emotion): {content}" (examples wrap dialogue in {}); never repeat words after a line with tone notes, which triggers subtitles. For exact on-screen text, spell letters to appear one by one, or supply the text as an image and add \'referring to Image N\'.') },
  ],
  examples: [
    { prompt: 'Image 1 is the knight, Image 2 is the castle courtyard; the knight uses the voice in Audio 1. 0-4s: low-angle tracking shot, he strides to the gate. 4-8s: close-up, he says: {Open the gate.} No subtitles.', note: '多素材参考：按编号逐个绑定素材用途，用首尾相接的整秒时间戳分段，对白用 {}，用否定写法去掉字幕', modes: ['omni'] },
    { prompt: 'Edit Video 1: from 3-6s, change the man\'s action from reading a newspaper to pouring tea, and replace his jacket with the coat in Image 1. Keep everything else unchanged.', note: '视频编辑：带编辑触发词，写明范围和时间段，写成从 A 改为 B，并要求其余内容不变', modes: ['edit'] },
    { prompt: 'Extend Video 1 backward by 5 seconds: a paper boat drifts down a rain-soaked street toward the camera, low-angle follow shot. Only rain and street ambience, no BGM.', note: '视频延长：带延长触发词并点名要延长的视频，写明方向和时长，描述新增画面和运镜，用否定写法去掉 BGM', modes: ['extend'] },
  ],
};

export const SEEDANCE_20_GUIDE: PromptGuide = {
  id: 'seedance-2-0',
  title: T('Dreamina Seedance 2.0 系列提示词指南', 'Dreamina Seedance 2.0 series prompt guide'),
  source: { url: 'https://ai.byteplus.com/ark/region:ap-southeast-1/docs/seedance-2-0-prompt-guide', revision: 296, checkedAt: CHECKED_AT },
  summary: T('Seedance 2.0 的提示词要写成“工程式指令”：按“主体 → 动作 → 场景 → 光线色调 → 运镜 → 风格 → 画质 → 约束”的顺序写，复杂内容拆成 Shot 1/2/3 时间线分镜。素材按上传顺序以 Image/Video/Audio N 编号并定义主体标签；编辑或延长时直接写 Video N，不写 reference。另外用符号区分音乐、音效、对白和字幕，并用约束词压住字幕、水印和重复人物。', 'Seedance 2.0 prompts should read like engineering instructions: subject, action, scene, lighting/tone, camera, style, quality, then constraints, with complex videos written as a Shot 1/2/3 timeline. Assets are numbered Image/Video/Audio N in upload order and bound to subject labels. Edit/extend prompts name Video N directly (never \'reference Video N\'). Symbols mark music, sound effects, dialogue and subtitles, and constraint words suppress subtitles, watermarks and duplicated characters.'),
  rules: [
    { text: T('按“精确主体 + 动作细节 + 场景/环境 + 光线与色调 + 运镜 + 视觉风格 + 画质 + 约束”的顺序写：先定下谁在做什么，再交代在哪里、什么氛围，然后写怎么拍，最后用风格、画质、约束词收尾。描述要精简，不要直接把完整剧本贴进来。', 'Order the prompt as precise subject + action details + scene/environment + lighting & color tone + camera movement + visual style + image quality + constraints: who does what, then where and what mood, then how to shoot, then tighten with style, quality and constraints. Keep it concise; never paste a full script.') },
    { text: T('复杂视频写成时间线分镜，用 Shot 1 / Shot 2 / Shot 3 按事件发生顺序排列，主要内容在前。每个镜头依次写运镜或转场方式、主体动作与表情、位置或空间变化、音频信息。不要给每段硬性限定秒数（如 0–3 秒），精确时长控制不稳定。', 'Write complex videos as a timeline storyboard (Shot 1 / Shot 2 / Shot 3) in the order events happen, primary first. In each shot give camera movement or transition, subject action and expression, position/spatial change, then audio. Do not force per-shot durations (e.g. 0–3 s); precise timing is unstable.') },
    { text: T('按上传顺序用 Image N / Video N / Audio N（也可写 @Image N）引用素材，并说清从每个素材取什么。句式：Reference <主体> in Image N；Reference <动作/运镜/风格/音效> in Video N；Reference the timbre in Audio N。用素材库 Asset ID 时也要写 Image/Video N，不能直接写 Asset ID。', 'Refer to assets as Image N / Video N / Audio N (or @Image N) in upload order and state what each one provides: \'Reference <subject> in Image N\', \'Reference <action/camera movement/style/sound effect> in Video N\', \'Reference the timbre in Audio N\'. Even with Asset IDs, write Image/Video N, never the Asset ID.'), modes: ['omni'] },
    { text: T('素材里有多个主体时，先用 2–3 个稳定的静态特征（服装、发型、外貌、类别）把目标定义成唯一标签：Define [特征] in Image N as <标签>。同一主体出现在多个素材里时，绑到同一个标签；有多个主体时分别定义，标签互不相同。', 'When an asset holds several subjects, first bind the target to a unique label using 2–3 stable static features (clothing, hairstyle, appearance, category): \'Define [features] in Image N as <label>\'. Bind the same subject across multiple assets to one label; give each subject its own distinct label.'), modes: ['omni'] },
    { text: T('每次提到主体都要明确指代：没有预先定义的，写成“名字@Image N”（或“名字（corresponding to image N）”）；已经定义的，始终用同一个标签。同一主体不要写互相矛盾的特征，空间关系尽量交给参考图表达。', 'Name the subject explicitly every time: undefined subjects as \'Name@Image N\' (or \'Name (corresponding to image N)\'), defined subjects always with the same label. Avoid contradictory features for one subject, and let reference images carry spatial relationships instead of long text.'), modes: ['omni'] },
    { text: T('编辑视频时直接写 Video N，不要写 reference Video N，否则会被当成参考任务。修改写 Strictly edit Video N, change <原特征> to <新特征>。增加写清元素特征、出现时机和位置。删除写明要删什么，并强调哪些内容保持不变。参考一个素材再编辑另一个视频写 Reference [维度] of Image N, strictly edit Video X, [具体修改]。', 'For edits name Video N directly, never \'reference Video N\' (or it becomes a reference task). Modify: \'Strictly edit Video N, change <original> to <new>\'. Add: element features + timing + location. Remove: name what to delete and stress what stays unchanged. Combined: \'Reference [dimension] of Image N, strictly edit Video X, [edits]\'.'), modes: ['omni'] },
    { text: T('延长视频同样直接写 Video N。句式为 Extend Video N forward/backward + 延长内容，或 Generate content before/after Video N + 延长内容。多段衔接写成 Video 1 + 过渡描述 + followed by Video 2 + 过渡描述 + followed by Video 3，最多 3 段输入视频，合计不超过 15 秒。', 'For extension also name Video N directly: \'Extend Video N forward/backward + content\' or \'Generate content before/after Video N + content\'. To join clips: \'Video 1 + transition + followed by Video 2 + transition + followed by Video 3\'; at most 3 input videos totaling 15 s or less.'), modes: ['omni'] },
    { text: T('动作要具体到身体部位（手、腿、头、肩、背），并写出幅度、速度和力度。优先用慢、轻、连贯的小动作，少写冲刺、大跳、翻滚这类高爆发动作。前后动作之间写出惯性衔接。情绪用可见的身体细节来表现，不要写“很伤心”“非常生气”这类抽象词。', 'Describe actions per body part (hands, legs, head, shoulders, back) with range, speed and force. Prefer slow, gentle, continuous small movements over sprints, big jumps or violent rolls. Spell out the inertia linking consecutive actions. Show emotion through physical details instead of words like \'very sad\'.') },
    { text: T('直接用标准镜头术语，如 medium shot、close-up、wide shot、slow push-in、smooth lateral tracking、fixed shot。建议每个镜头优先只用一种运镜，避免同时堆叠推、拉、摇、移等多种要求。', 'Use standard camera terms directly (medium shot, close-up, wide shot, slow push-in, smooth lateral tracking, fixed shot) and preferably one camera movement per shot, avoiding stacking push, pull, pan and move at once.') },
    { text: T('结尾补三类词。画质词，如 HD、rich details、cinematic texture、soft lighting。风格词：明确写出目标风格（如 2D Japanese anime style），参考图偏写实时尤其要写，防止风格漂移。约束词，如 keep it subtitle-free、do not generate a logo、do not generate a watermark；多角色时再加“禁止出现外观完全相同的重复人物或双胞胎效果”。', 'End with quality words (HD, rich details, cinematic texture, soft lighting), an explicit target style (e.g. \'2D Japanese anime style\', essential when references look realistic, to stop style drift), and constraints: \'keep it subtitle-free\', \'do not generate a logo\', \'do not generate a watermark\', plus a no-duplicate/twin-character constraint when there are several characters.') },
    { text: T('用符号区分信息类型：音乐放（），音效放 < >，对白放 { }，字幕放【】。对白语言要统一，不要中英混用（专有名词除外）。中英文以外的小语种对白要标明语言，如 says in Japanese {…}。中文多音字、生僻字容易读错，可改写成读音相同的常用字。', 'Mark information types with symbols: music in （）, sound effects in < >, dialogue in { }, subtitles in 【】. Keep dialogue in one language without mixing Chinese and English (proper nouns excepted); label other languages, e.g. \'says in Japanese {…}\'. Replace easily misread Chinese characters with common homophones.') },
    { text: T('建议素材总数控制在 4–5 个（如 1–2 张人物图 + 1 张场景图 + 1 段运镜视频 + 1 段音频），不必用满上限。人物参考建议用只含头部的面部特写加全身照，不用三视图或多视图；提示词里写明“<主体> facial features reference Image 1, styling reference Image 2”。越需要精确参考的素材越靠前写。同时参考的人物超过 4 个时稳定性会下降，可以先分组出图，再拿这些图生成视频。', 'A recommended setup is 4–5 assets in total (e.g. 1–2 character images + 1 scene image + 1 camera video + 1 audio), rather than the full limit. Prefer a headshot plus a full-body photo per character over three-view or multi-view sheets, and state \'<Subject> facial features reference Image 1, styling reference Image 2\'. Mention the most precise references first. Stability drops beyond 4 referenced people; for more, generate grouped images first, then make the video from them.'), modes: ['omni'] },
    { text: T('需要画面文字时，写成“[文字内容] + [出现时机] + [位置] + [出现方式], [颜色/字体]”。字幕写 Display subtitles at the bottom-center…，并要求与音频节奏同步。对话气泡写 [角色] says, "…". Speech bubbles appear around the character…。文字尽量用常用字，避开生僻字和特殊符号。', 'For on-screen text write \'[text] + [timing] + [position] + [entrance style], [color/font]\'; subtitles: \'Display subtitles at the bottom-center…\' synchronized with the audio; speech bubbles: \'[Character] says, "…". Speech bubbles appear around the character…\'. Use common characters, avoiding rare characters and special symbols.') },
    { text: T('特效的形式或运动逻辑难以用文字控制时，建议给一段参考视频，写 Refer to the [特效] from Video N…, keeping the special effects consistent（如“数字 2999 的出现方式参考 Video 1”）。用参考音频指定音色时，在提示词里补充音色特征（如 the low, thick, warm middle-aged male voice of Audio 1），台词风格也要贴近参考音频。', 'When an effect\'s form or motion is hard to control with text, it is recommended to provide a reference video: \'Refer to the [effect] from Video N…, keeping the special effects consistent\'. When cloning a voice from Audio N, describe the timbre in the prompt (e.g. \'the low, thick, warm middle-aged male voice of Audio 1\') and keep the lines\' style close to the reference audio.'), modes: ['omni'] },
  ],
  examples: [
    { prompt: 'Define the woman in a red coat in Image 1 as Mia. Shot 1: medium shot, Mia walks slowly into the cafe from Image 2. Shot 2: slow push-in, she lowers her head and smiles softly. HD, warm tones, keep it subtitle-free.', note: '全模态参考：先定义主体标签，再用 Shot 分镜写动作和运镜，最后加画质和约束词', modes: ['omni'] },
    { prompt: 'Strictly edit Video 1: change the blue mug on the desk to the red teapot from Image 1, keeping all other content, motion and camera work unchanged. Do not generate a watermark or logo.', note: '2.0 在全模态参考里做视频编辑：直接写 Video 1（不写 reference），写明原特征、新特征和保持不变的部分', modes: ['omni'] },
    { prompt: 'Shot 1: wide shot, an old fisherman slowly rows across a misty lake at dawn <oars splashing>. Shot 2: close-up, he gently raises his head and says {We are almost home}. Cinematic, soft light, no subtitles.', note: '文生视频：Shot 分镜、每镜一种运镜、慢速小动作，音效用 <>，对白用 {}，结尾加风格和防字幕约束', modes: ['t2v'] },
  ],
};

export const SEEDANCE_15_GUIDE: PromptGuide = {
  id: 'seedance-1-5-pro',
  title: T('Seedance 1.5 pro 提示词指南', 'Seedance-1.5-pro prompt guide'),
  source: { url: 'https://ai.byteplus.com/ark/region:ap-southeast-1/docs/seedance-1-5-pro', revision: 296, checkedAt: CHECKED_AT },
  summary: T('按"主体 + 动作 + 环境 + 运镜 + 美学 + 声音"组织提示词，主体和动作写具体，并用程度副词控制动作。1.5 pro 是音画联合生成模型：对白写成"说话人标签 + 引号台词"，注明语言和情绪/语调/语速；音效直接描写发声的事件，BGM 写风格、情绪和节奏。多镜头用 cut 标出切换点；运镜按"起止构图 + 方式 + 幅度"写，景别按"主体 + 景别"写；风格要给出明确参照。', 'Structure prompts as Subject + Movement (+ Environment, Camera, Aesthetic, Sound), with concrete subjects and degree adverbs for motion. As a joint audio-video model, Seedance 1.5 pro takes dialogue as speaker-labelled quoted lines with explicit language and emotion/tone/pace; SFX are described as sound-making events and BGM by style, mood and rhythm. Mark multi-shot cuts explicitly, describe camera moves as start composition + move + amplitude + end composition, write shot size as subject + size, and name explicit style references.'),
  rules: [
    { text: T('按“主体 + 动作 + 环境（可选）+ 运镜（可选）+ 美学风格（可选）+ 声音（可选）”的顺序组织提示词，主体和动作必写，其余按需补充。', 'Structure the prompt as Subject + Movement, then optionally Environment, Camera movement, Aesthetic style and Sound, in that order.') },
    { text: T('提示词用中文或英文写；分辨率、比例、时长、seed、固定机位、水印用参数（params）设置，不要在提示词末尾追加 --rs / --dur / --cf 之类的文本命令。', 'Write the prompt in Chinese or English; set resolution, ratio, duration, seed, fixed camera and watermark via params, not with --rs / --dur / --cf text commands at the end of the prompt.') },
    { text: T('主体和动作要写具体、有约束：给出外貌、服装、表情等关键特征和画面里必须出现的视觉要点，用程度副词（slowly、powerfully）和先后顺序（first…then…）控制动作的幅度与节奏。', 'Describe subject and motion concretely: give key traits (look, outfit, expression) and the must-show visual cues, and use degree adverbs (slowly, powerfully) and sequencing (first…then…) to control motion amplitude and rhythm.') },
    { text: T('同一个主体在全文用同一组特征来称呼（如 the Indian woman），多角色时才不会混淆；文字要和想要的画面、声音一一对应。', 'Refer to each subject with the same feature-based label throughout (e.g. "the Indian woman") so characters stay distinct, and keep the text aligned with both the intended visuals and audio.') },
    { text: T('首帧图生视频时，可以用 "Based on this image" 或 "the input image" 指代输入图；明确写出接下来的动作和变化，以及需要保持一致的外观特征；要求忠实保留原图时，可以注明不添加无关元素。', 'In first-frame image-to-video you can refer to the input as "this image" or "the input image"; describe the upcoming action and change and the features that must stay consistent; when the original must be preserved faithfully, you can add that no unrelated elements be added.'), modes: ['i2v_first'] },
    { text: T('对白写成 Speaker: "台词" 或 he says: "…"，台词放在双引号里；多人对话先交代每个角色的性别、年龄、服装、动作等区分特征，口型才会对到正确的人。', 'Write dialogue as Speaker: "line" (or he says: "…") with the line in double quotes; in multi-person scenes first give each speaker distinguishing traits (gender, age, clothing, action) so lip-sync lands on the right person.') },
    { text: T('写明对白语言（如 "English dialogue:"、"He said in Cantonese"），台词直接用该语言的原文写。支持普通话、粤语、四川话、陕西话、台湾腔，以及英语、日语、韩语、西班牙语、印尼语。', 'State the dialogue language explicitly (e.g. "English dialogue:", "He said in Cantonese") and write the lines in that language; supported: Mandarin, Cantonese, Sichuan, Shaanxi, Taiwanese accent, English, Japanese, Korean, Spanish, Indonesian.') },
    { text: T('要控制声音表现时，在台词前写情绪、语调、语速（如 In a gentle emotional state, with a soft tone and a slow speaking pace, say: "…"）；旁白要写明音色和性别（如 A deep, calm male voice says…）。', 'Control delivery by stating emotion, tone and speaking pace before the line (e.g. "In a gentle emotional state, with a soft tone and a slow speaking pace, say: …"); for voiceover name the voice (e.g. "A deep, calm male voice says…").') },
    { text: T('音效直接描写发声的画面事件（雨势变大、油库爆炸）。背景音乐默认按提示词自动生成，要控制时写明曲风或乐器、情绪，以及画面动作与音乐节奏的关系（如随鼓点拍手）。', 'For SFX, describe the sound-making event itself (rain getting heavier, a fuel depot exploding); BGM is auto-generated by default, so to steer it state the style or instruments, the mood, and how the action syncs to it (e.g. clapping on the drumbeats).') },
    { text: T('多镜头按时间顺序逐个写，每个镜头写明景别和内容，用 "The shot cuts to… / cuts back to…" 或 "Shot 1: … Shot 2: …" 标出切换点；对话场景可以按说话人做正反打切换。', 'For multi-shot videos write shots in order, each with shot size and content, marking cuts with "The shot cuts to… / cuts back to…" or "Shot 1: … Shot 2: …"; dialogue scenes can alternate shot/reverse-shot per speaker.') },
    { text: T('运镜按“起始构图 + 运镜方式 + 运镜幅度 + 结束构图”写。常用词有 dolly-in/dolly-out、pan、track、follow、rise、fall、whirl、rotate、surround、zoom，可以组合使用（希区柯克变焦 = dolly + 反向 zoom，子弹时间 = 慢动作 + 环绕）。', 'Write camera moves as starting composition + movement + amplitude + ending composition, using dolly-in/out, pan, track, follow, rise, fall, whirl, rotate, surround, zoom; combine them (Hitchcock = dolly + opposite zoom; bullet time = slow motion + surround).') },
    { text: T('视角和景别用摄影术语：机位写 high angle、low angle、eye-level、bird view；叙事视角写 over-the-shoulder、subjective、surveillance、telescope；主体朝向写 front、profile、back。景别按“主体 + 景别”写，如 Close-up of the man on the left。', 'Use photographic terms for angle and framing: camera angle (high/low/eye-level/bird view), narrative view (over-the-shoulder, subjective, surveillance, telescope), subject facing (front/profile/back); write shot size as subject + size, e.g. "Close-up of the man on the left".') },
    { text: T('要特定画风时，给出明确的风格参照（如 Imitate the style of Hayao Miyazaki\'s anime、the style of Disney\'s 2D animated movies），比只堆形容词更能准确传达氛围和色调。', 'For a distinct look, name an explicit style reference (e.g. "Imitate the style of Hayao Miyazaki\'s anime", "the style of Disney\'s 2D animated movies") rather than relying on adjectives alone.') },
    { text: T('特效或变身类画面要写清触发时机、变化过程和变化后的细节，并兼顾配套的声音设计。', 'For effects or transformations, spell out the trigger moment, the transformation process and the resulting details, and consider the accompanying audio design.') },
  ],
  examples: [
    { prompt: 'A gray-haired fisherman in a yellow raincoat mends a net on a foggy pier, then slowly looks up. The camera dollies in from a medium shot to a close-up. English dialogue: Fisherman: "Storm is coming early this year."', note: '文生视频：主体特征 + 动作先后 + 运镜起止构图 + 标明语言的引号对白', modes: ['t2v'] },
    { prompt: 'Based on this image, the barista slowly pours milk into the cup, forming a leaf pattern; keep her face and apron consistent, add nothing else. Steady close-up. Soft cafe chatter and a gentle piano BGM.', note: '首帧图生视频：用 this image 指代输入图，只写变化，写明要保持一致的内容，并写环境音和 BGM 风格', modes: ['i2v_first'] },
    { prompt: 'Shot 1: Medium shot of two hikers on a cliff at dawn. Shot 2: Cut to a close-up of the woman, who whispers in a calm tone, "We made it." Shot 3: Cut back to a wide shot as the sun rises. Style of Hayao Miyazaki anime.', note: '多镜头：Shot 编号加 cut 标切换，每个镜头写景别，对白写语气，最后给明确的风格参照', modes: ['t2v'] },
  ],
};

export const SEEDANCE_10_GUIDE: PromptGuide = {
  id: 'seedance-1-0-pro',
  title: T('Seedance 1.0 pro / pro fast 提示词指南', 'Seedance-1.0-pro&pro-fast prompt guide'),
  source: { url: 'https://ai.byteplus.com/ark/region:ap-southeast-1/docs/seedance-1-0-pro-pro-fast', revision: 296, checkedAt: CHECKED_AT },
  summary: T('提示词以“主体 + 动作”为基础，多个动作按发生的时间顺序写；用运镜词（推/拉/摇/移/环绕/跟随/升/变焦）、景别和视角词控制镜头，可以把几种运镜串成一镜到底，也可以在一条提示词里用 “Camera switch” 切多个镜头；再用风格词、视频类型和自然语言写的氛围描述控制美感。支持中文和英文；本平台用参数（params）设置分辨率、时长和固定机位，不要再在提示词末尾追加对应的文本命令。', 'Build prompts on subject + action, writing multiple actions in the order they happen; steer the camera with movement words (push/pull/pan/move/circle/follow/rise/zoom), shot sizes and angles, chain moves into a single long take, or cut between shots in one prompt with "Camera switch"; control the look with style words, a video-type label and natural-language atmosphere. Chinese and English are supported; this platform sets resolution, duration and fixed camera via params, so do not also append the matching text commands to the prompt.'),
  rules: [
    { text: T('基础写法是“主体 + 动作”：一句话写清谁在做什么（例如小猫对着镜头打哈欠）。', 'Start from subject + action: one clear sentence stating who does what (e.g. the kitten yawns at the camera).') },
    { text: T('多个动作按发生的时间顺序依次写，用 then 等词连接；多人场景给每个角色分别写出各自的动作。', 'Write multiple actions in the order they happen, linked with words like \'then\'; in multi-character scenes give each character their own action.') },
    { text: T('图生视频直接用图中主体的称呼（the man / the woman / the boy）开头，写它接下来的动作和变化；官方 i2v 示例都没用 Image 1 这类编号去引用图片。', 'For image-to-video, refer to the subject in the image directly (the man / the woman / the boy) and describe its next actions and changes; the official i2v examples never use labels like \'Image 1\'.'), modes: ['i2v_first', 'i2v_first_last'] },
    { text: T('运镜用明确的镜头动词，并写出方向和快慢，例如 camera quickly pushes into / pulls out / pans right / moves right / circles around / follows / rises / zoom lens。', 'Use explicit camera verbs with direction and speed: the camera quickly pushes in / pulls out / pans right / moves right / circles around / follows / rises, or a zoom lens.') },
    { text: T('用专业术语指定景别（long shot / full shot / medium shot / close-up）和视角（aerial、high-angle、low-angle、underwater、macro、over-the-shoulder、以某物为前景或透过某物拍摄）。', 'Name the shot size (long / full / medium shot, close-up) and the angle (aerial, high-angle, low-angle, underwater, macro, over-the-shoulder, with X in the foreground or shooting through X).') },
    { text: T('需要一镜到底时，按顺序串联多个运镜：先写起始机位，再把每次运镜和主体的动作对应起来（starts from… follows… then tilts upward… finally zooms in）。', 'For a single long take, chain several camera moves in order: state the starting position, then tie each move to the subject\'s action (starts from… follows… then tilts up… finally zooms in).') },
    { text: T('一条提示词可以包含多个镜头，镜头之间用 “Camera switch.” 或 scene switch 连接；切换后如果出现新角色或新场景，要描写它们的特征。', 'One prompt can hold several shots joined by \'Camera switch.\' / scene switch; after each switch, describe any newly appearing characters or scenes.') },
    { text: T('文生视频可以直接指定风格，风格词写在句首，例如 3D cartoon: / Japanese manga: / Voxel style, / American comic style，或者写 felt、clay、pixel、illustration、black-and-white line drawing 等材质或画风。', 'Text-to-video can output styles directly: lead with the style, e.g. \'3D cartoon:\', \'Japanese manga:\', \'Voxel style,\', \'American comic style\', or felt, clay, pixel, illustration, line-drawing looks.'), modes: ['t2v'] },
    { text: T('细致描写人物外貌、服装和场景；想要不好看或不完美的长相就直接写出具体特征（plain-looking、略胖的脸、痣、粗糙的皮肤、300 磅）。', 'Describe characters, clothing and setting in detail; for non-idealized looks state concrete traits (plain-looking, chubby face, a mole, rough skin, 300-pound).') },
    { text: T('用视频类型句控制画面质感（It\'s a European art-house film / retro Hong Kong film / horror movie / festive rustic short video），也可以用自然语言写正面或负面的氛围（textured old movie、1980s TV drama with cheap makeup）。', 'Set the look with a video-type line (It\'s a European art-house film / retro Hong Kong film / horror movie / festive rustic short video) or natural-language atmosphere, positive or negative.') },
    { text: T('写特效或变身类内容时，把变化的过程逐步写出来（as time passes / gradually … until …），并补充伴随的细节（烟雾、光、碎片飞出画面）。', 'For effects and transformations, spell out the progression (as time passes / gradually … until …) and the accompanying details (smoke, light, parts flying out of frame).') },
    { text: T('提示词支持中文和英文。', 'Prompts may be written in Chinese or English.') },
    { text: T('分辨率、时长、是否固定机位用参数（params）设置；官方也支持在提示词末尾追加 --resolution / --duration / --camerafixed 文本命令，但本平台已经通过参数发送，两处不要同时写。', 'Set resolution, duration and fixed camera via params; the official text commands (--resolution / --duration / --camerafixed appended to the prompt) also exist, but this platform already sends the params — do not use both.') },
    { text: T('首帧和尾帧图片最好用 1:1、3:4、4:3、16:9、9:16、21:9 这几种比例；不符合时会被自动裁剪到最接近的比例。', 'Prefer first/last-frame images in 1:1, 3:4, 4:3, 16:9, 9:16 or 21:9; others are auto-cropped to the closest supported ratio.'), modes: ['i2v_first', 'i2v_first_last'] },
  ],
  examples: [
    { prompt: 'A street drummer in a red cap twirls his sticks, strikes the drum hard, then grins at the crowd. The camera slowly pushes in from a low angle to a close-up of his face. A warm, retro Hong Kong film.', note: '文生视频：主体加按时间顺序写的多个动作，再加带方向和速度的运镜、视角、景别，最后用一句视频类型控制质感', modes: ['t2v'] },
    { prompt: 'The old woman sets down her teacup, turns her head toward the window, and smiles. The camera pans left to reveal rain streaking the glass. It is a quiet European art-house film.', note: '图生视频：直接用图中主体的称呼写后续动作（不用 Image 1 编号），再加一个运镜和视频类型句', modes: ['i2v_first', 'i2v_first_last'] },
    { prompt: 'Clay animation style: a clay fox runs through a snowy forest. Camera switch. Close-up of the fox sniffing a glowing mushroom. Camera switch. Aerial shot of the fox curled up asleep under the stars.', note: '文生视频多镜头：风格词放在句首，用 Camera switch 连接三个镜头，每个镜头写景别或视角', modes: ['t2v'] },
  ],
};

/** 各 Seedance 模型对应的指南 */
export const SEEDANCE_PROMPT_GUIDES: Record<SeedanceKey, PromptGuide[]> = {
  v25: [SEEDANCE_25_GUIDE],
  v20: [SEEDANCE_20_GUIDE],
  v20fast: [SEEDANCE_20_GUIDE],
  v20mini: [SEEDANCE_20_GUIDE],
  v15pro: [SEEDANCE_15_GUIDE],
  v10pro: [SEEDANCE_10_GUIDE],
  v10fast: [SEEDANCE_10_GUIDE],
};

/** 各 Seedream 模型对应的指南：4.x 指南正文只写 4.0 / 4.5；5.0 lite 没有官方指南覆盖 */
export const SEEDREAM_PROMPT_GUIDES: Record<SeedreamKey, PromptGuide[]> = {
  pro: [SEEDREAM_50_EDITING_GUIDE],
  flash: [SEEDREAM_50_EDITING_GUIDE],
  lite: [],
  v45: [SEEDREAM_4X_GUIDE],
  v40: [SEEDREAM_4X_GUIDE],
};

/**
 * 按模型实际有的模式裁剪指南（同一份指南会挂到模式不同的几个模型上，例如 1.0 pro fast 没有首尾帧模式）：
 * 只算用户写提示词的模式（派生模式如「生成正片」沿用样片提示词，不适用）；
 * 规则 / 示范的 modes 取交集，交集为空的条目不挂到这个模型上
 */
export function scopeGuides(guides: PromptGuide[], modes: ModeDef[]): PromptGuide[] {
  const userModes = modes.filter((m) => m.entry !== 'derived').map((m) => m.id);
  return guides.map((g) => {
    // 指南自身声明了适用模式时，与模型的模式取交集
    const modeIds = g.modes?.length ? userModes.filter((m) => g.modes!.includes(m)) : userModes;
    const has = new Set(modeIds);
    const scope = <T extends { modes?: string[] }>(items: T[]): T[] =>
      items.flatMap((item) => {
        if (!item.modes?.length) return [item];
        const kept = item.modes.filter((m) => has.has(m));
        return kept.length ? [{ ...item, modes: kept }] : [];
      });
    return { ...g, modes: modeIds, rules: scope(g.rules), ...(g.examples ? { examples: scope(g.examples) } : {}) };
  });
}
